#line 1 "lex.yy.c"

#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[211] =
    {   0,
        0,    0,   46,   44,   41,   40,   44,   39,   44,   44,
       44,   44,   24,   25,   17,   15,    7,   16,   44,   18,
       34,   44,   19,   27,   26,   29,   44,   44,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,    8,    9,
       44,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   44,   44,   37,   44,   42,   43,   31,    0,   36,
        0,   13,    1,    0,    4,   12,   11,   32,    0,    0,
       34,   35,   35,   14,   28,   26,    2,   30,   21,   23,
        0,   20,    3,   22,    0,   37,   37,   37,    2,    0,
       37,   37,   37,    4,   37,   37,   37,   37,   37,   20,

        3,    3,   33,   37,   37,   37,   37,   37,   37,   10,
       37,   37,   37,   37,    3,   37,   37,   37,   37,   33,
        0,    5,    6,    0,    0,   35,    0,    0,   32,    1,
       37,   37,   37,   37,    6,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
        0,   38,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   12,   37,   37,   37,   37,   37,   37,   37,
       37,   10,   37,   37,    1,    0,   37,   37,   21,   37,
       37,   37,   37,   37,   37,   37,   22,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   13,   37,

       37,   37,    5,   37,   37,   37,   11,   37,   23,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    8,    1,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   29,   30,   31,
       32,   33,   34,   28,   28,   35,   36,   37,   38,   39,
       28,   40,   41,   42,   28,   28,   43,   28,   44,   45,
       46,    1,   47,    1,   48,    1,   49,   50,   50,   51,

       52,   53,   54,   55,   56,   50,   50,   57,   58,   59,
       60,   61,   50,   62,   63,   64,   50,   50,   65,   50,
       66,   50,    1,   67,    1,   68,    1,    1,   28,   69,
        1,    1,    1,    1,    1,   28,   70,    1,    1,    1,
       28,    1,    1,    1,   28,    1,   28,    1,    1,    1,
        1,    1,    1,   28,    1,   28,   50,    1,    1,    1,
       71,    1,    1,   28,   50,    1,    1,    1,   50,    1,
        1,   28,   50,    1,    1,    1,   50,    1,   50,   28,
       50,    1,    1,    1,    1,   50,    1,    1,    1,    1,
       72,    1,    1,   73,   70,   70,   70,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    1,    3,    3,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    1,    3,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    5,
        5,    3,    3,    1
    } ;

static const flex_int16_t yy_base[214] =
    {   0,
        0,    0,  229, 1031, 1031,  223,  218, 1031,  195,   68,
       69,  206, 1031, 1031,  185, 1031, 1031,   61,   63, 1031,
       67,  161, 1031,   73,  159,   76,  141,   70,   71,   85,
       87,   92,   97,  105,  141,  147,  150,  152, 1031, 1031,
      132,  113,  168,  160,  175,  178,  186,  191,  214,  194,
      217,   87,  129,  222,   79, 1031, 1031, 1031,  173, 1031,
      181, 1031,  124,  113, 1031, 1031, 1031, 1031,  111,   99,
      231, 1031,  155, 1031, 1031, 1031, 1031, 1031, 1031, 1031,
       57, 1031, 1031, 1031,   53,  241,  249,  256,  258,  260,
      262,  264,  281,  272,  275,  296,  317,  321,  283,  330,

      337,  340,  342,  353,  357,  355,  374,  363,  365, 1031,
      380,  390,  398,  411,  421,  423,  438,  436,  444, 1031,
       48, 1031, 1031,   96,  189,  172,   35,   28,  446,  448,
      471,  454,  461,  494,  459,  503,  508,  517,  520,  527,
      535,  544,  551,  548,  563,  575,  582,  567,  584,  594,
      622,   81,  620,  631,  638,  641,  647,  654,  657,  659,
      664,  674,  685,  700,  697,  702,  712,  717,  720,  723,
      735,  728,  733,  743,   72,   63,  761,  766,  778,  782,
      789,  793,  799,  802,  814,  816,  805,  809,  820,  825,
      837,  848,  862,  864,  869,  879,  875,  882,  885,  887,

      890,  902,  895,  940,  923,  943,  906,  948,  950, 1031,
     1018, 1020, 1025
    } ;

static const flex_int16_t yy_def[214] =
    {   0,
      210,    1,  210,  210,  210,  210,  210,  210,  210,  211,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  210,  210,
      210,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  210,  210,  212,  210,  210,  210,  210,  211,  210,
      211,  210,  210,  210,  210,  210,  210,  210,  213,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,  210,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  210,
      210,  210,  210,  213,  213,  210,  210,  210,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      210,  213,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  210,  210,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,

      212,  212,  212,  212,  212,  212,  212,  212,  212,    0,
      210,  210,  210
    } ;

static const flex_int16_t yy_nxt[1106] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       30,   33,   30,   34,   30,   30,   30,   35,   30,   36,
       37,   30,   38,   30,   30,   39,   40,   41,   42,   30,
       43,   44,   30,   45,   30,   46,   47,   30,   30,   48,
       30,   49,   50,   30,   51,   30,   52,   53,    4,   54,
       30,    4,    4,   55,   60,   62,   70,   83,   71,   71,
       72,   72,   73,   77,   71,   71,  123,   74,   86,   86,
       63,   84,   64,  122,   65,   75,   58,  125,   78,   83,

       79,   80,   86,   86,   86,   86,   77,   88,   66,   86,
       86,   89,  125,   67,   86,   86,   72,   72,   90,  151,
       93,  128,   86,   86,   94,  127,   98,  125,   96,   91,
       86,   86,   90,   89,   90,  100,  123,   61,   61,   90,
       92,  101,   95,   85,   90,  122,   94,  121,   99,   81,
       97,   58,   90,  120,   92,  110,   92,  100,   86,   86,
       90,   92,   82,  102,   86,   86,   92,   86,   86,   86,
       86,  111,  126,  126,   92,   89,  104,   86,   86,   60,
      103,   76,   92,   74,  108,   86,   86,   60,   90,  126,
      126,  106,   86,   86,   90,   86,   86,   90,  105,   90,

      152,   69,  103,   86,   86,  125,  109,   90,   86,   86,
       92,   86,   86,  107,   68,   90,   92,   58,  113,   92,
       57,   92,   90,  112,   56,   90,  114,   94,  210,   92,
      100,   86,   86,   90,   86,   86,  115,   92,   90,   86,
       86,   90,   61,   61,   92,  116,   73,   92,   71,   71,
       61,   61,  103,  210,  210,   92,  210,  118,   86,   86,
       92,   90,  210,   92,   90,  117,   86,   86,  210,   90,
      210,  119,  210,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   92,  129,  210,   92,  210,   90,   86,
       86,   92,   86,   86,  210,  210,   90,  210,   86,   86,

       86,   86,  210,   90,  210,   90,  210,  210,  210,   90,
       92,   90,  129,   86,   86,  210,  130,  210,   92,   90,
      210,  131,   90,  210,  133,   92,  210,   92,   90,   92,
       90,   92,  130,   92,   86,   86,  210,  132,   86,   86,
      210,   92,  210,   90,   92,  210,  135,   86,   86,  210,
       92,  210,   92,  210,   86,   86,  210,   86,   86,   86,
       86,  210,  135,  210,   90,   92,  210,  134,   90,  210,
       86,   86,   86,   86,   86,   86,  210,   90,  136,  138,
       86,   86,   86,   86,   90,  210,   92,   90,  210,   90,
       92,   86,   86,  210,  140,  210,  142,   86,   86,   92,

       90,  210,   90,  137,   90,  139,   92,   86,   86,   92,
       90,   92,   90,  210,  210,   86,   86,  210,  210,  210,
      143,   90,   92,  210,   92,  210,   92,   90,   86,   86,
      129,  210,   92,  210,   92,  141,  210,   90,   86,   86,
       86,   86,  210,   92,  210,   90,  210,  130,  145,   92,
      210,  210,  144,   86,   86,   86,   86,  210,   90,   92,
      210,   86,   86,   86,   86,   86,   86,   92,   90,  210,
       90,   86,   86,  210,  135,  210,   86,   86,   86,   86,
       92,  147,  210,   90,  146,   90,  148,  210,   86,   86,
       92,   90,   92,   90,  155,   90,  210,  149,  210,  150,

      210,   90,  210,  156,  210,   92,   90,   92,   90,  153,
      210,   86,   86,   92,  154,   92,  210,   92,   90,  210,
       86,   86,  210,   92,  210,   86,   86,  157,   92,  210,
       92,  210,  161,  210,   86,   86,  158,   86,   86,  210,
       92,   90,  210,  210,   86,   86,  210,  210,  210,  159,
       90,  163,   86,   86,  210,   90,  210,  210,  160,  162,
      164,   86,   86,   92,   90,   86,   86,   90,   86,   86,
      210,  210,   92,  210,   90,  210,  163,   92,  166,  210,
       86,   86,   90,  210,   86,   86,   92,  210,  210,   92,
      165,   90,   86,   86,  210,   90,   92,  210,   90,   86,

       86,   86,   86,  210,   92,  210,  210,  167,  168,  210,
       90,   86,   86,   92,   90,  210,  210,   92,  169,  210,
       92,  210,   90,  163,  210,  210,  171,  170,   62,   90,
      210,   90,   92,  210,  210,  172,   92,   86,   86,  173,
      210,   90,  210,  175,   92,  176,  210,   65,   86,   86,
      174,   92,  210,   92,  177,   86,   86,  210,   86,   86,
      210,   66,  210,   92,   86,   86,   67,   90,  179,  210,
      210,   86,   86,  180,   86,   86,   86,   86,   90,  210,
      210,   86,   86,  210,  210,   90,  210,  178,   90,   92,
      210,   86,   86,  210,   90,  183,  210,  210,  210,  179,

       92,   90,   86,   86,   90,  210,   90,   92,  181,  179,
       92,   90,  210,  182,   86,   86,   92,   86,   86,   86,
       86,   90,  210,   92,  210,  210,   92,  184,   92,   86,
       86,  187,   90,   92,   86,   86,  185,   86,   86,  210,
       86,   86,  210,   92,   90,   86,   86,   90,  210,   90,
       86,   86,   86,   86,   92,  186,  210,  210,  210,   90,
       86,   86,  210,  187,   90,  210,   92,   90,  210,   92,
       90,   92,  179,  188,  210,   90,  210,  189,   86,   86,
       90,   92,   90,   86,   86,  210,   92,  192,  190,   92,
       90,  191,   92,  210,  187,   86,   86,   92,  210,   86,

       86,  210,   92,  210,   92,  210,   86,   86,   90,  210,
       86,   86,   92,   90,  193,  194,   86,   86,  210,   86,
       86,  210,   86,   86,  210,   90,   86,   86,  197,   90,
       92,   86,   86,   86,   86,   92,   90,   86,   86,  210,
       90,  210,   86,   86,  195,  199,   90,   92,  196,   90,
      210,   92,   90,  198,   86,   86,   90,  200,   92,  210,
      210,   90,   92,   90,  210,   86,   86,   90,   92,  199,
      210,   92,   90,  210,   92,  201,  202,  210,   92,   86,
       86,   86,   86,   92,   90,   92,   86,   86,  210,   92,
      199,  203,   86,   86,   92,   90,   86,   86,  204,   86,

       86,  210,   86,   86,   86,   86,   92,   86,   86,   90,
      210,   90,   86,   86,  207,  210,   90,   92,  210,   86,
       86,  210,   90,   86,   86,  205,   90,  203,  210,   90,
      210,   92,   90,   92,   90,  206,  210,   90,   92,  210,
       86,   86,   90,  207,   92,  210,  208,  210,   92,   90,
      210,   92,  203,   90,   92,  210,   92,   86,   86,   92,
       86,   86,  210,  207,   92,   86,   86,   86,   86,  209,
       90,   92,  210,  210,  209,   92,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,   90,  210,  210,
       90,  210,   92,  210,  209,   90,  210,   90,  210,  209,

      210,  210,  210,  210,  210,  210,  210,  210,  210,   92,
      210,  210,   92,  210,  210,  210,  210,   92,  210,   92,
       59,  210,   59,   87,   87,  124,  210,  124,  124,  124,
        3,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,

      210,  210,  210,  210,  210
    } ;

static const flex_int16_t yy_chk[1106] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   10,   11,   18,   28,   18,   18,
       19,   19,   21,   26,   21,   21,  176,   24,   29,   29,
       11,   28,   11,  175,   11,   24,   24,  152,   26,  128,

       26,   26,   30,   30,   31,   31,  127,   29,   11,   32,
       32,   29,  124,   11,   33,   33,   70,   70,   29,  121,
       31,   85,   34,   34,   31,   81,   33,   69,   32,   29,
       42,   42,   30,   29,   31,   34,   64,   10,   10,   32,
       29,   34,   31,   28,   33,   63,   31,   55,   33,   26,
       32,   53,   34,   52,   30,   41,   31,   34,   35,   35,
       42,   32,   27,   34,   36,   36,   33,   37,   37,   38,
       38,   42,   73,   73,   34,   42,   36,   44,   44,   59,
       35,   25,   42,   22,   38,   43,   43,   61,   35,  126,
      126,   37,   45,   45,   36,   46,   46,   37,   36,   38,

      125,   15,   35,   47,   47,  125,   38,   44,   48,   48,
       35,   50,   50,   37,   12,   43,   36,    9,   44,   37,
        7,   38,   45,   43,    6,   46,   45,   43,    3,   44,
       46,   49,   49,   47,   51,   51,   46,   43,   48,   54,
       54,   50,   59,   59,   45,   47,   71,   46,   71,   71,
       61,   61,   48,    0,    0,   47,    0,   50,   86,   86,
       48,   49,    0,   50,   51,   49,   87,   87,    0,   54,
        0,   51,    0,   88,   88,   89,   89,   90,   90,   91,
       91,   92,   92,   49,   88,    0,   51,    0,   86,   94,
       94,   54,   95,   95,    0,    0,   87,    0,   93,   93,

       99,   99,    0,   88,    0,   89,    0,   90,    0,   91,
       86,   92,   91,   96,   96,    0,   93,    0,   87,   94,
        0,   93,   95,    0,   96,   88,    0,   89,   93,   90,
       99,   91,   95,   92,   97,   97,    0,   95,   98,   98,
        0,   94,    0,   96,   95,    0,   99,  100,  100,    0,
       93,    0,   99,    0,  101,  101,    0,  102,  102,  103,
      103,    0,   98,    0,   97,   96,    0,   97,   98,    0,
      104,  104,  106,  106,  105,  105,    0,  100,  101,  104,
      108,  108,  109,  109,  101,    0,   97,  102,    0,  103,
       98,  107,  107,    0,  106,    0,  108,  111,  111,  100,

      104,    0,  106,  102,  105,  105,  101,  112,  112,  102,
      108,  103,  109,    0,    0,  113,  113,    0,    0,    0,
      109,  107,  104,    0,  106,    0,  105,  111,  114,  114,
      111,    0,  108,    0,  109,  107,    0,  112,  115,  115,
      116,  116,    0,  107,    0,  113,    0,  112,  113,  111,
        0,    0,  112,  118,  118,  117,  117,    0,  114,  112,
        0,  119,  119,  129,  129,  130,  130,  113,  115,    0,
      116,  132,  132,    0,  114,    0,  135,  135,  133,  133,
      114,  116,    0,  118,  115,  117,  117,    0,  131,  131,
      115,  119,  116,  129,  133,  130,    0,  118,    0,  119,

        0,  132,    0,  133,    0,  118,  135,  117,  133,  131,
        0,  134,  134,  119,  132,  129,    0,  130,  131,    0,
      136,  136,    0,  132,    0,  137,  137,  134,  135,    0,
      133,    0,  136,    0,  138,  138,  134,  139,  139,    0,
      131,  134,    0,    0,  140,  140,    0,    0,    0,  134,
      136,  138,  141,  141,    0,  137,    0,    0,  134,  137,
      140,  142,  142,  134,  138,  144,  144,  139,  143,  143,
        0,    0,  136,    0,  140,    0,  139,  137,  142,    0,
      145,  145,  141,    0,  148,  148,  138,    0,    0,  139,
      141,  142,  146,  146,    0,  144,  140,    0,  143,  147,

      147,  149,  149,    0,  141,    0,    0,  143,  144,    0,
      145,  150,  150,  142,  148,    0,    0,  144,  145,    0,
      143,    0,  146,  148,    0,    0,  146,  145,  151,  147,
        0,  149,  145,    0,    0,  147,  148,  153,  153,  149,
        0,  150,    0,  151,  146,  151,    0,  151,  154,  154,
      150,  147,    0,  149,  153,  155,  155,    0,  156,  156,
        0,  151,    0,  150,  157,  157,  151,  153,  155,    0,
        0,  158,  158,  156,  159,  159,  160,  160,  154,    0,
        0,  161,  161,    0,    0,  155,    0,  154,  156,  153,
        0,  162,  162,    0,  157,  161,    0,    0,    0,  157,

      154,  158,  163,  163,  159,    0,  160,  155,  158,  159,
      156,  161,    0,  160,  165,  165,  157,  164,  164,  166,
      166,  162,    0,  158,    0,    0,  159,  162,  160,  167,
      167,  166,  163,  161,  168,  168,  164,  169,  169,    0,
      170,  170,    0,  162,  165,  172,  172,  164,    0,  166,
      173,  173,  171,  171,  163,  165,    0,    0,    0,  167,
      174,  174,    0,  167,  168,    0,  165,  169,    0,  164,
      170,  166,  169,  168,    0,  172,    0,  170,  177,  177,
      173,  167,  171,  178,  178,    0,  168,  177,  171,  169,
      174,  173,  170,    0,  174,  179,  179,  172,    0,  180,

      180,    0,  173,    0,  171,    0,  181,  181,  177,    0,
      182,  182,  174,  178,  178,  180,  183,  183,    0,  184,
      184,    0,  187,  187,    0,  179,  188,  188,  183,  180,
      177,  185,  185,  186,  186,  178,  181,  189,  189,    0,
      182,    0,  190,  190,  181,  185,  183,  179,  182,  184,
        0,  180,  187,  184,  191,  191,  188,  188,  181,    0,
        0,  185,  182,  186,    0,  192,  192,  189,  183,  186,
        0,  184,  190,    0,  187,  189,  190,    0,  188,  193,
      193,  194,  194,  185,  191,  186,  195,  195,    0,  189,
      191,  192,  197,  197,  190,  192,  196,  196,  194,  198,

      198,    0,  199,  199,  200,  200,  191,  201,  201,  193,
        0,  194,  203,  203,  197,    0,  195,  192,    0,  202,
      202,    0,  197,  207,  207,  195,  196,  193,    0,  198,
        0,  193,  199,  194,  200,  196,    0,  201,  195,    0,
      205,  205,  203,  198,  197,    0,  201,    0,  196,  202,
        0,  198,  200,  207,  199,    0,  200,  204,  204,  201,
      206,  206,    0,  202,  203,  208,  208,  209,  209,  204,
      205,  202,    0,    0,  205,  207,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  204,    0,    0,
      206,    0,  205,    0,  206,  208,    0,  209,    0,  208,

        0,    0,    0,    0,    0,    0,    0,    0,    0,  204,
        0,    0,  206,    0,    0,    0,    0,  208,    0,  209,
      211,    0,  211,  212,  212,  213,    0,  213,  213,  213,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,

      210,  210,  210,  210,  210
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[46] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexico.l"
#line 2 "Lexico.l"
  #include <stdio.h>
  #include <stdlib.h>
  #include "y.tab.h"
  #include "ts.h"

  int lineno = 1;

  int MIN_INT = -32768;
  int MAX_INT = 32767;
  double MIN_REAL = -2147483648.0;
  double MAX_REAL = 2147483647.0;
  int MAX_STRING = 30;

  int yyerror(char *);
#line 802 "lex.yy.c"
/*
 * Operators
 */
/*
 * Comparators
 */
/*
 * Identifier
 */
/*
 * Constants
 */
/*
 * Reserved Words
 */
/*
 * Specials
 */
/*
 * Types
 */
/*
 * Groupers
 */
/*
 * Separators
 */
/*
 * Comment
 */
#line 833 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 126 "Lexico.l"

#line 1052 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 211 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1031 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 127 "Lexico.l"
{
  return op_dim;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 130 "Lexico.l"
{
  return op_as;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 134 "Lexico.l"
{
  return op_in;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 137 "Lexico.l"
{
  return op_do;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 141 "Lexico.l"
{
  return op_display;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 144 "Lexico.l"
{
  return op_get;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 148 "Lexico.l"
{
  return dec_separator;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 152 "Lexico.l"
{
  return open_dec;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 155 "Lexico.l"
{
  return close_dec;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 159 "Lexico.l"
{
  return fun_long;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 163 "Lexico.l"
{
  return int_type;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 166 "Lexico.l"
{
  return real_type;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 169 "Lexico.l"
{
  return string_type;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 173 "Lexico.l"
{
  return op_assign;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 177 "Lexico.l"
{
  return op_sum;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 180 "Lexico.l"
{
  return op_sub;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 183 "Lexico.l"
{
  return op_mult;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 186 "Lexico.l"
{
  return op_div;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 190 "Lexico.l"
{
  return separator;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 194 "Lexico.l"
{
  return op_if;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 197 "Lexico.l"
{
  return op_endif;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 201 "Lexico.l"
{
  return op_while;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 204 "Lexico.l"
{
  return op_endwhile;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 208 "Lexico.l"
{
  return open_parenthesis;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 211 "Lexico.l"
{
  return close_parenthesis;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 215 "Lexico.l"
{
  return op_eq;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 218 "Lexico.l"
{
  return op_lt;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 221 "Lexico.l"
{
  return op_le;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 224 "Lexico.l"
{
  return op_gt;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 227 "Lexico.l"
{
  return op_ge;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 230 "Lexico.l"
{
  return op_ne;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 234 "Lexico.l"
{
  return op_and;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 237 "Lexico.l"
{
  return op_or;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 241 "Lexico.l"
{
  int value = strtol(yytext,(char **)NULL,10);

  char msg[MAX_STRING + strlen(yytext)];

  if(value < MIN_INT) {
    sprintf(msg, "integer constant out of range: %s, min: %d", yytext, MIN_INT);

    yyerror(msg);
  }
  
  else if(value > MAX_INT) {
    sprintf(msg, "integer constant out of range: %s, max: %d", yytext, MAX_INT);

    yyerror(msg);
  }
  
  else {
    yylval.int_val = value;
  }

  loadToTS(yytext, constant_int);

  return int_constant;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 266 "Lexico.l"
{
  double value = atof(yytext);

  char msg[MAX_STRING + strlen(yytext)];

  if (value < MIN_REAL || value > MAX_REAL) {
    sprintf(
      msg,
      "real constant out of range: %s, min: %f, max: %f",
      yytext, MIN_REAL, MAX_REAL
    );

    yyerror(msg);
  }

  yylval.real_val = value;

  loadToTS(yytext, constant_real);

  return real_constant;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 288 "Lexico.l"
{
  int STRING_LENGTH = strlen(yytext);

  char msg[STRING_LENGTH + MAX_STRING];

  if(STRING_LENGTH > MAX_STRING) {
    sprintf(
      msg,
      "string out of range: %s, length: %d, max: %d",
      yytext, STRING_LENGTH, MAX_STRING
    );

    yyerror(msg);
  }

  yylval.str_val = yytext;
  
  loadToTS(yytext, constant_str);

  return string_constant;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 310 "Lexico.l"
{
  int STRING_LENGTH = strlen(yytext);

  char msg[STRING_LENGTH + MAX_STRING];

  if(STRING_LENGTH > MAX_STRING) {
    sprintf(
      msg,
      "id out of range: %s, length: %d, max: %d",
      yytext, STRING_LENGTH, MAX_STRING
    );

    yyerror(msg);
  }

  yylval.str_val = yytext;

  loadToTS(yytext, identifier);

  return id;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 332 "Lexico.l"
/* skip comments */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 334 "Lexico.l"

	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 335 "Lexico.l"
{
  ++lineno;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 338 "Lexico.l"

	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 339 "Lexico.l"

	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 340 "Lexico.l"

	YY_BREAK
case 44:
YY_RULE_SETUP
#line 342 "Lexico.l"
{
  char s[] = "invalid character: ";

  strcat(s, yytext);
  strcat(s, "\n");

  yyerror(s);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 350 "Lexico.l"
ECHO;
	YY_BREAK
#line 1506 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 211 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 211 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 210);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 350 "Lexico.l"

